#!/bin/sh

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

src=/etc/modprobe.d/nvidia-graphics-drivers.conf
[ "${verbose}" = "y" ] && echo "Dereferencing and copying ${src}"

cp -pL --remove-destination "${src}" "${DESTDIR}${src}"

