#!/bin/sh

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

cp -pL --remove-destination "/lib/nvidia-375/modprobe.conf" "${DESTDIR}/etc/modprobe.d/nvidia-graphics-drivers.conf"

