NVIDIA-Linux/libnvcuvid.so.450.216.04                   usr/lib/aarch64-linux-gnu
NVIDIA-Linux/libnvidia-opticalflow.so.450.216.04        usr/lib/aarch64-linux-gnu
NVIDIA-Linux/libvdpau_nvidia.so.450.216.04              usr/lib/aarch64-linux-gnu/vdpau
#NVIDIA-Linux/32/libnvcuvid.so.450.216.04                    usr/lib/aarch64-linux-gnu
#NVIDIA-Linux/32/libnvidia-opticalflow.so.450.216.04         usr/lib/aarch64-linux-gnu
#NVIDIA-Linux/32/libvdpau_nvidia.so.450.216.04               usr/lib/aarch64-linux-gnu/vdpau
