NVIDIA-Linux/libnvcuvid.so.550.22                   usr/lib/aarch64-linux-gnu
NVIDIA-Linux/libnvidia-opticalflow.so.550.22        usr/lib/aarch64-linux-gnu
NVIDIA-Linux/libvdpau_nvidia.so.550.22              usr/lib/aarch64-linux-gnu/vdpau
#NVIDIA-Linux/32/libnvcuvid.so.550.22                    usr/lib/aarch64-linux-gnu
#NVIDIA-Linux/32/libnvidia-opticalflow.so.550.22         usr/lib/aarch64-linux-gnu
#NVIDIA-Linux/32/libvdpau_nvidia.so.550.22               usr/lib/aarch64-linux-gnu/vdpau
