NVIDIA-Linux/libnvcuvid.so.${env:NVIDIA_RELEASE}                   usr/lib/${DEB_HOST_MULTIARCH}
NVIDIA-Linux/libnvidia-opticalflow.so.${env:NVIDIA_RELEASE}        usr/lib/${DEB_HOST_MULTIARCH}
NVIDIA-Linux/libvdpau_nvidia.so.${env:NVIDIA_RELEASE}              usr/lib/${DEB_HOST_MULTIARCH}/vdpau
#NVIDIA-Linux/32/libnvcuvid.so.${env:NVIDIA_RELEASE}                    usr/lib/${DEB_HOST_MULTIARCH}
#NVIDIA-Linux/32/libnvidia-opticalflow.so.${env:NVIDIA_RELEASE}         usr/lib/${DEB_HOST_MULTIARCH}
#NVIDIA-Linux/32/libvdpau_nvidia.so.${env:NVIDIA_RELEASE}               usr/lib/${DEB_HOST_MULTIARCH}/vdpau
