NVIDIA-Linux/libnvidia-ml.so.384.111                                 usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libcuda.so.384.111                                      usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libnvidia-opencl.so.384.111                             usr/lib/x86_64-linux-gnu
NVIDIA-Linux/nvidia.icd                                              etc/OpenCL/vendors
NVIDIA-Linux/libnvidia-fatbinaryloader.so.384.111                    usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libnvidia-ptxjitcompiler.so.384.111                     usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libnvidia-compiler.so.384.111                           usr/lib/x86_64-linux-gnu
