NVIDIA-Linux/32/libcuda.so.430.26                                 usr/lib/x86_64-linux-gnu/nvidia/libs-i386
NVIDIA-Linux/32/libnvidia-fatbinaryloader.so.430.26               usr/lib/x86_64-linux-gnu/nvidia/libs-i386
NVIDIA-Linux/32/libnvidia-ptxjitcompiler.so.430.26                usr/lib/x86_64-linux-gnu/nvidia/libs-i386
NVIDIA-Linux/32/libnvidia-ml.so.430.26                            usr/lib/x86_64-linux-gnu/nvidia/libs-i386
NVIDIA-Linux/32/libnvidia-compiler.so.430.26                      usr/lib/x86_64-linux-gnu/nvidia/libs-i386
NVIDIA-Linux/32/libnvidia-opencl.so.430.26                        usr/lib/x86_64-linux-gnu/nvidia/libs-i386
