NVIDIA-Linux/libnvidia-ml.so.410.73                               usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libcuda.so.410.73                                    usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libnvidia-opencl.so.410.73                           usr/lib/x86_64-linux-gnu
NVIDIA-Linux/nvidia.icd                                  etc/OpenCL/vendors
NVIDIA-Linux/libnvidia-fatbinaryloader.so.410.73                  usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libnvidia-ptxjitcompiler.so.410.73                   usr/lib/x86_64-linux-gnu
NVIDIA-Linux/libnvidia-compiler.so.410.73                         usr/lib/x86_64-linux-gnu
