NVIDIA-Linux/libnvcuvid.so.510.47.03                   usr/lib/aarch64-linux-gnu
NVIDIA-Linux/libnvidia-opticalflow.so.510.47.03        usr/lib/aarch64-linux-gnu
NVIDIA-Linux/libvdpau_nvidia.so.510.47.03              usr/lib/aarch64-linux-gnu/vdpau
#NVIDIA-Linux/32/libnvcuvid.so.510.47.03                    usr/lib/aarch64-linux-gnu
#NVIDIA-Linux/32/libnvidia-opticalflow.so.510.47.03         usr/lib/aarch64-linux-gnu
#NVIDIA-Linux/32/libvdpau_nvidia.so.510.47.03               usr/lib/aarch64-linux-gnu/vdpau
