NVIDIA-Linux/libcuda.so.390.25                                    usr/lib/i386-linux-gnu
NVIDIA-Linux/libnvidia-fatbinaryloader.so.390.25                  usr/lib/i386-linux-gnu
NVIDIA-Linux/libnvidia-ptxjitcompiler.so.390.25                   usr/lib/i386-linux-gnu
NVIDIA-Linux/libnvidia-ml.so.390.25                               usr/lib/i386-linux-gnu
NVIDIA-Linux/libnvidia-compiler.so.390.25           usr/lib/i386-linux-gnu
NVIDIA-Linux/libnvidia-opencl.so.390.25             usr/lib/i386-linux-gnu
