NVIDIA-Linux/libnvidia-ml.so.390.151                               usr/lib/aarch64-linux-gnu
NVIDIA-Linux/libcuda.so.390.151                                    usr/lib/aarch64-linux-gnu
NVIDIA-Linux/libnvidia-opencl.so.390.151             usr/lib/aarch64-linux-gnu
NVIDIA-Linux/nvidia.icd                                etc/OpenCL/vendors
NVIDIA-Linux/libnvidia-fatbinaryloader.so.390.151                  usr/lib/aarch64-linux-gnu
NVIDIA-Linux/libnvidia-ptxjitcompiler.so.390.151                   usr/lib/aarch64-linux-gnu
NVIDIA-Linux/libnvidia-compiler.so.390.151           usr/lib/aarch64-linux-gnu
