NVIDIA-Linux-x86_64-256.35-no-compat32/libXvMCNVIDIA.a       /usr/lib/nvidia-current

NVIDIA-Linux-x86_64-256.35-no-compat32/cl*.h                                /usr/include/nvidia-current/CL
NVIDIA-Linux-x86_64-256.35-no-compat32/gl*.h                                /usr/include/nvidia-current/GL
NVIDIA-Linux-x86_64-256.35-no-compat32/cuda*.h                              /usr/include/nvidia-current/cuda
