debian/nvidia-current-experimental.override                 usr/share/lintian/overrides
#Blacklist some card ids from GRUB gfxpayload=keep
debian/nvidia-current-experimental.grub-gfxpayload          /usr/share/nvidia-current-experimental

NVIDIA-Linux-x86_64-304.43-no-compat32/nvidia_drv.so /usr/lib/nvidia-current-experimental/xorg
NVIDIA-Linux-x86_64-304.43-no-compat32/libglx.so.304.43 /usr/lib/nvidia-current-experimental/xorg

NVIDIA-Linux-x86_64-304.43-no-compat32/libGL*.so*                  /usr/lib/nvidia-current-experimental
NVIDIA-Linux-x86_64-304.43-no-compat32/libnv*.so*                  /usr/lib/nvidia-current-experimental
NVIDIA-Linux-x86_64-304.43-no-compat32/libcuda*.so*                /usr/lib/nvidia-current-experimental
NVIDIA-Linux-x86_64-304.43-no-compat32/libOpenCL*.so*              /usr/lib/nvidia-current-experimental

NVIDIA-Linux-x86_64-304.43-no-compat32/libvdpau_nvidia.so*   /usr/lib/nvidia-current-experimental/vdpau
NVIDIA-Linux-x86_64-304.43-no-compat32/tls/*.so*                   /usr/lib/nvidia-current-experimental/tls

NVIDIA-Linux-x86_64-304.43-no-compat32/libXvMCNVIDIA.so.304.43  /usr/lib/nvidia-current-experimental

debian/temp/modules/nvidia-kernel/kernel/*    usr/src/nvidia-current-experimental-304.43
debian/dkms/patches/*                         usr/src/nvidia-current-experimental-304.43/patches
debian/dkms.conf                              usr/src/nvidia-current-experimental-304.43

NVIDIA-Linux-x86_64-304.43-no-compat32/nvidia-bug-report.sh /usr/lib/nvidia-current-experimental/bin
NVIDIA-Linux-x86_64-304.43-no-compat32/nvidia-xconfig /usr/lib/nvidia-current-experimental/bin
NVIDIA-Linux-x86_64-304.43-no-compat32/nvidia-smi /usr/lib/nvidia-current-experimental/bin

NVIDIA-Linux-x86_64-304.43-no-compat32/nvidia-current-experimental-settings.png /usr/share/pixmaps

debian/ubuntu-nvidia-settings.desktop   /usr/share/nvidia-current-experimental

debian/nvidia-autostart.desktop /usr/share/nvidia-current-experimental

NVIDIA-Linux-x86_64-304.43-no-compat32/nvidia.icd /usr/share/nvidia-current-experimental
