debian/71-nvidia.rules                                               lib/udev/rules.d
debian/create-uvm-dev-node                                           sbin
debian/dkms.conf                                                     usr/src/nvidia-390.48
debian/dkms_nvidia/patches/*                                         usr/src/nvidia-390.48/patches
debian/framebuffer-nvidia                                            usr/share/initramfs-tools/hooks
debian/nvidia-graphics-drivers.conf                                  etc/modprobe.d
