debian/nvidia-experimental-310.override                 usr/share/lintian/overrides
#Blacklist some card ids from GRUB gfxpayload=keep
debian/nvidia-experimental-310.grub-gfxpayload          /usr/share/nvidia-experimental-310

NVIDIA-Linux-x86_64-310.12/nvidia_drv.so /usr/lib/nvidia-experimental-310/xorg
NVIDIA-Linux-x86_64-310.12/libglx.so.310.12 /usr/lib/nvidia-experimental-310/xorg

NVIDIA-Linux-x86_64-310.12/libGL*.so*                  /usr/lib/nvidia-experimental-310
NVIDIA-Linux-x86_64-310.12/libnv*.so*                  /usr/lib/nvidia-experimental-310
NVIDIA-Linux-x86_64-310.12/libcuda*.so*                /usr/lib/nvidia-experimental-310
NVIDIA-Linux-x86_64-310.12/libOpenCL*.so*              /usr/lib/nvidia-experimental-310

NVIDIA-Linux-x86_64-310.12/libvdpau_nvidia.so*   /usr/lib/nvidia-experimental-310/vdpau
NVIDIA-Linux-x86_64-310.12/tls/*.so*                   /usr/lib/nvidia-experimental-310/tls

debian/temp/modules/nvidia-kernel/kernel/*    usr/src/nvidia-experimental-310-310.12
debian/dkms/patches/*                         usr/src/nvidia-experimental-310-310.12/patches
debian/dkms.conf                              usr/src/nvidia-experimental-310-310.12

NVIDIA-Linux-x86_64-310.12/nvidia-bug-report.sh /usr/lib/nvidia-experimental-310/bin
NVIDIA-Linux-x86_64-310.12/nvidia-xconfig /usr/lib/nvidia-experimental-310/bin
NVIDIA-Linux-x86_64-310.12/nvidia-smi /usr/lib/nvidia-experimental-310/bin

NVIDIA-Linux-x86_64-310.12/nvidia-experimental-310-settings.png /usr/share/pixmaps

debian/ubuntu-nvidia-settings.desktop   /usr/share/nvidia-experimental-310

debian/nvidia-autostart.desktop /usr/share/nvidia-experimental-310

NVIDIA-Linux-x86_64-310.12/nvidia.icd /usr/share/nvidia-experimental-310
