debian/nvidia-current-updates.override                 usr/share/lintian/overrides
#Blacklist some card ids from GRUB gfxpayload=keep
debian/nvidia-current-updates.grub-gfxpayload          /usr/share/nvidia-current-updates

NVIDIA-Linux-x86-304.32/nvidia_drv.so /usr/lib/nvidia-current-updates/xorg
NVIDIA-Linux-x86-304.32/libglx.so.304.32 /usr/lib/nvidia-current-updates/xorg

NVIDIA-Linux-x86-304.32/libGL*.so*                  /usr/lib/nvidia-current-updates
NVIDIA-Linux-x86-304.32/libnv*.so*                  /usr/lib/nvidia-current-updates
NVIDIA-Linux-x86-304.32/libcuda*.so*                /usr/lib/nvidia-current-updates
NVIDIA-Linux-x86-304.32/libOpenCL*.so*              /usr/lib/nvidia-current-updates

NVIDIA-Linux-x86-304.32/libvdpau_nvidia.so*   /usr/lib/nvidia-current-updates/vdpau
NVIDIA-Linux-x86-304.32/tls/*.so*                   /usr/lib/nvidia-current-updates/tls

NVIDIA-Linux-x86-304.32/libXvMCNVIDIA.so.304.32  /usr/lib/nvidia-current-updates

debian/dkms/patches/*                         usr/src/nvidia-current-updates-304.32/patches
debian/dkms.conf                              usr/src/nvidia-current-updates-304.32
debian/temp/modules/nvidia-kernel/kernel/*    usr/src/nvidia-current-updates-304.32

NVIDIA-Linux-x86-304.32/nvidia-bug-report.sh /usr/lib/nvidia-current-updates/bin
NVIDIA-Linux-x86-304.32/nvidia-xconfig /usr/lib/nvidia-current-updates/bin
NVIDIA-Linux-x86-304.32/nvidia-smi /usr/lib/nvidia-current-updates/bin

NVIDIA-Linux-x86-304.32/nvidia-current-updates-settings.png /usr/share/pixmaps

debian/ubuntu-nvidia-settings.desktop   /usr/share/nvidia-current-updates

debian/nvidia-autostart.desktop /usr/share/nvidia-current-updates

NVIDIA-Linux-x86-304.32/nvidia.icd /usr/share/nvidia-current-updates
